# Generated by Django 4.1.6 on 2023-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PVCellData',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('w', models.FloatField(default=0)),
            ],
        ),
    ]
