# Generated by Django 4.1.6 on 2023-03-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appData', '0002_rename_w_pvcelldata_hz_pvcelldata_iac_pvcelldata_idc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvcelldata',
            name='datetime',
        ),
    ]
